name: expense_tracker
description: Smart Personal Finance Management App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.12.0
  image_picker: ^1.2.1
  fl_chart: ^1.1.1
  intl: ^0.20.2
  go_router: ^17.0.1
  flutter_riverpod: ^3.1.0
  dio: ^5.4.0
  shared_preferences: ^2.5.4
  cupertino_icons: ^1.0.8
  speech_to_text: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
